huellador/Models/ErrorViewModel.cs
using System;

namespace huellador.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

huellador/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace huellador.Controllers
{
    public class AccountController : Controller
    {
        // GET: /<controller>/
        public IActionResult Account()
        {
            return View();
        }
    }
}

huellador/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace huellador.Controllers
{
    public class AdminController : Controller
    {
        // GET: /<controller>/
        public IActionResult PackageView()
        {
            return View();
        }

        public IActionResult OrganizationView()
        {
            return View();
        }

        public IActionResult UserView()
        {
            return View();
        }
    }
}

huellador/Controllers/CreditsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace huellador.Controllers
{
    public class CreditsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

huellador/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using huellador.Models;

namespace huellador.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

huellador/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace huellador.Controllers
{
    public class LoginController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login(){
            return View();
        }
    }
}

huellador/Controllers/MyPeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace huellador.Controllers
{
    public class MyPeopleController : Controller
    {
        // GET: /<controller>/
        public IActionResult PersonDisplay()
        {
            return View();
        }

        public IActionResult PrintDisplay()
        {
            return View();
        }
    }
}

huellador/Views/Admin/OrganizationView.cshtml
<div style="background-color:red; width:100%">
    <section class="hero is-primary" style="margin-bottom:20px">
        <div class="hero-body">
            <div class="columns">
                <div class="column">
                    <h1 class="title">
                        Organization View
                    </h1>
                    <h2 class="subtitle">
                        Add, edit and delete organizations.
                    </h2>
                </div>
                <div class="column">
                    <a href="./OrganizationView" class="button is-primary">Edit Organizations</a>
                    <a href="./UserView" class="button">Edit Users</a>
                    <a href="./PackageView" class="button">Edit Packages</a>

                </div>
            </div>
        </div>
    </section>
    <style>
        table>.button {
            color: black !important
        }
    </style>
    <div style="overflow-x: auto;">
        <table class="table is-striped is-narrow" style="margin:auto">
            <thead>
                <tr>
                    <th>Organization ID</th>
                    <th>Name</th>
                    <th>Credits</th>
                    <th>Phone</th>
                    <th>Owner</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>O1</td>
                    <td>FBI</td>
                    <td>901100</td>
                    <td>5251-2515</td>
                    <td>FBI Secret Man</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O2</td>
                    <td>ITESM</td>
                    <td>20</td>
                    <td>1420-5203</td>
                    <td>Migue</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O3</td>
                    <td>Polytechnique au France </td>
                    <td>150</td>
                    <td>4201-4201</td>
                    <td>Mr. PHD Pista</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O1</td>
                    <td>FBI</td>
                    <td>901100</td>
                    <td>5251-2515</td>
                    <td>FBI Secret Man</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O2</td>
                    <td>ITESM</td>
                    <td>20</td>
                    <td>1420-5203</td>
                    <td>Migue</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O3</td>
                    <td>Polytechnique au France </td>
                    <td>150</td>
                    <td>4201-4201</td>
                    <td>Mr. PHD Pista</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O1</td>
                    <td>FBI</td>
                    <td>901100</td>
                    <td>5251-2515</td>
                    <td>FBI Secret Man</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O2</td>
                    <td>ITESM</td>
                    <td>20</td>
                    <td>1420-5203</td>
                    <td>Migue</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O3</td>
                    <td>Polytechnique au France </td>
                    <td>150</td>
                    <td>4201-4201</td>
                    <td>Mr. PHD Pista</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O1</td>
                    <td>FBI</td>
                    <td>901100</td>
                    <td>5251-2515</td>
                    <td>FBI Secret Man</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O2</td>
                    <td>ITESM</td>
                    <td>20</td>
                    <td>1420-5203</td>
                    <td>Migue</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
                <tr>
                    <td>O3</td>
                    <td>Polytechnique au France </td>
                    <td>150</td>
                    <td>4201-4201</td>
                    <td>Mr. PHD Pista</td>
                    <td>
                        <a class="button">Add Credits </a>
                    </td>
                    <td>
                        <a class="button is-danger">Delete Organization</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

huellador/Views/Admin/PackageView.cshtml
<section class="hero is-primary" style="margin-bottom:20px">
        <div class="hero-body">
          <div class="columns">
              <div class="column">
            <h1 class="title">
              Edit coin packages
            </h1>
            <h2 class="subtitle">
              Change the system's prices
            </h2></div>
            <div class="column">
              <a href="./OrganizationView" class="button">Edit Organizations</a>
              <a href="./UserView" class="button">Edit Users</a>
              <a href="./PackageView" class="button is-primary">Edit Packages</a>
      
            </div>
          </div>
        </div>
      </section>

<div class="columns">
    <div class="column">
        <table class="table">
            <thead>
                <tr>
                    <th>Package</th>
                    <th>Coins</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Paq 1</td>
                    <td>
                        <input placeholder="100" class="input" type="text">
                    </td>
                    <td>
                        <input placeholder="$120,000.00" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Paq 2</td>
                    <td>
                        <input placeholder="100" class="input" type="text">
                    </td>
                    <td>
                        <input placeholder="$120,000.00" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Paq 3</td>
                    <td>
                        <input placeholder="100" class="input" type="text">
                    </td>
                    <td>
                        <input placeholder="$120,000.00" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Paq 4</td>
                    <td>
                        <input placeholder="100" class="input" type="text">
                    </td>
                    <td>
                        <input placeholder="$120,000.00" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Paq 5</td>
                    <td>
                        <input placeholder="100" class="input" type="text">
                    </td>
                    <td>
                        <input placeholder="$120,000.00" class="input" type="text">
                    </td>
                </tr>
            </tbody>
        </table>
        <a class="button">Save</a>
    </div>
    <div class="column">
        <table class="table">
            <thead>
                <tr>
                    <th>Package</th>
                    <th>Coins</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Verification</td>
                    <td>
                        <input placeholder="20" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Verification 2</td>
                    <td>
                        <input placeholder="20" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Comparison</td>
                    <td>
                        <input placeholder="20" class="input" type="text">
                    </td>
                </tr>
                <tr>
                    <td>Comparison 2</td>
                    <td>
                        <input placeholder="20" class="input" type="text">
                    </td>
                </tr>
            </tbody>
        </table>
        <a class="button">Save</a>
    </div>

</div>

huellador/Views/Admin/UserView.cshtml
<section class="hero is-primary" style="margin-bottom:20px">
  <div class="hero-body">
    <div class="columns">
        <div class="column">
      <h1 class="title">
        User Admin
      </h1>
      <h2 class="subtitle">
        Add, edit and delete users.
      </h2></div>
      <div class="column">
        <a href="./OrganizationView" class="button">Edit Organizations</a>
        <a href="./UserView" class="button is-primary">Edit Users</a>
        <a href="./PackageView" class="button">Edit Packages</a>

      </div>
    </div>
  </div>
</section>

<style>
.black{
    color:black !important}
</style>
<div style="overflow-x: auto;">
<table class="table is-striped is-narrow" style="margin:auto" >
    <thead>
        <tr>
            <th>User ID</th>
            <th>Name</th>
            <th>Organization</th>
            <th>Is Admin?</th>
            <th>Credits</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Daniel</td>
            <td>ITESM</td>
            <td>Yes</td>
            <td>200</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
            <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Ottmar</td>
            <td>FBI</td>
            <td>No</td>
            <td>10</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Florian</td>
            <td>Polytechnique au France</td>
            <td>Yes</td>
            <td>2000</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr class="is-selected">
            <td>1</td>
            <td>Daniel</td>
            <td>ITESM</td>
            <td>Yes</td>
            <td>200</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Ottmar</td>
            <td>FBI</td>
            <td>No</td>
            <td>10</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Florian</td>
            <td>Polytechnique au France</td>
            <td>Yes</td>
            <td>2000</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>        <tr>
            <td>1</td>
            <td>Daniel</td>
            <td>ITESM</td>
            <td>Yes</td>
            <td>200</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Ottmar</td>
            <td>FBI</td>
            <td>No</td>
            <td>10</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Florian</td>
            <td>Polytechnique au France</td>
            <td>Yes</td>
            <td>2000</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>        
        <tr>
            <td>1</td>
            <td>Daniel</td>
            <td>ITESM</td>
            <td>Yes</td>
            <td>200</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Ottmar</td>
            <td>FBI</td>
            <td>No</td>
            <td>10</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Florian</td>
            <td>Polytechnique au France</td>
            <td>Yes</td>
            <td>2000</td>
            <td><a class="button black">Make Admin </a></td>
            <td><a class="button black">Add Credits </a></td>
             <td><a class="button is-danger">Delete User</a></td>
        </tr>
    </tbody>
</table>    

huellador/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

huellador/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

huellador/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1> This is Home bois</h1>
</div>

huellador/Views/Login/Login.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <style>
        html {
            background-image: url("https://banknxt.com/wp-content/uploads/2017/03/Finger-pay-redux.jpg");
            width: 100%;
            height: 100%;
            background-size: cover;
            font: white;
        }

        .whiteFinger {
            color: white;
            font-size: 15px;
        }

        .whiteHuella {
            color: white;
            font-size: 40px;
        }

        .white {
            color: white;
            font-size: 15px;
        }

        .fondoVerde {
            width: 450px;
            background-color: cadetblue;
            margin: auto;
            margin-top: 100px;
            padding: 40px;
            border-radius: 20px;
        }

        .centrado {
            width: 300px;
            margin: auto;
        }

        .justificado {
            margin: 0px 35px 0px;
        }

        .justificado2 {
            margin: 0px 0px 0px;
        }

        .centrarBoton {
            margin: 0px 0px 0px;
        }

        .borde {
            border-bottom-style: groove;
            border-top-style: groove;
            border-left-style: groove;
            border-right-style: groove;
            border-width: 3px;
            border-radius: 7px;
            padding-left: 125px;
            padding-right: 125px;
            margin-bottom: 20px;
            margin-top: 20px;
        }
    </style>

    <div class="fondoVerde">
        <div class="logo columns">
            <div class="column is-one-quarter justificado2">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Fingerprint_picture.svg/200px-Fingerprint_picture.svg.png" height="300" width="300">
            </div>
            <div class="column justificado2 whiteHuella">
                <p class="whiteHuella">Huellador <br /></p>
                <p class="whiteFinger">Finger print recognition</p>
            </div>
        </div>
        <div class="formulario white">
            <label class="label justificado white">Email</label>
            <div class="control has-icons-left has-icons-right centrado">
                <input class="input is-left" type="email" placeholder="e-mail" value="">
                <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                </span>
                <span class="icon is-small is-right"></span>
            </div>
            <label class="label justificado white">Password</label>
            <div class="centrado"><input class="input" type="text" placeholder="Password"></div>
            <div class="justificado borde">
                <a class=" white" href="www.google.com">Submit</a>
            </div>
        </div>
        <div class="justificado">
            <a class="white" href="www.google.com">Forgot your password?</a><br />
            <div class="white">Don't have an account?  <a class="white" href="https://www.google.com.mx/?gfe_rd=cr&dcr=0&ei=VylpWvGmJdHj8Aej0YmoDA&gws_rd=ssl">Sign up</a></div>
        </div>
    </div>
</div>

huellador/Views/Login/SignUp.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div>
    <style>
        .fondoVerdeIzquierdo {
            width: 450px;
            background-color: cadetblue;
            margin: auto;
            margin-top: 100px;
            padding: 40px;
            border-bottom-left-radius: 20px;
            border-top-left-radius: 20px;
        }

        .fondoVerdeDerecho {
            width: 450px;
            background-color: cadetblue;
            margin: auto;
            margin-top: 100px;
            padding: 40px;
            border-bottom-right-radius: 20px;
            border-top-right-radius: 20px;
        }

        html {
            background-image: url("https://banknxt.com/wp-content/uploads/2017/03/Finger-pay-redux.jpg");
            width: 100%;
            height: 100%;
            background-size: cover;
            font: white;
        }

        .whiteFinger {
            color: white;
            font-size: 15px;
        }

        .whiteHuella {
            color: white;
            font-size: 40px;
        }

        .white {
            color: white;
            font-size: 15px;
        }

        .centrado {
            width: 300px;
            margin: auto;
        }

        .centro {
            margin: 0px 100px 0px;
        }

        .justificado {
            margin: 0px 35px 0px;
        }

        .justificadoUploadI {
            margin: 0px 10px 0px 10px;
        }

        .justificadoUpload {
            margin: 0px 150px 0px 150px;
        }

        .Forgot {
            margin-bottom: 20px;
        }

        .borde {
            border-bottom-style: groove;
            border-top-style: groove;
            border-left-style: groove;
            border-right-style: groove;
            border-width: 3px;
            border-radius: 7px;
            padding-left: 125px;
            padding-right: 125px;
            margin-bottom: 20px;
            margin-top: 20px;
        }

        .bordeDerecho {
            border-bottom-style: groove;
            border-top-style: groove;
            border-left-style: groove;
            border-right-style: groove;
            border-width: 3px;
            border-radius: 7px;
            padding-left: 125px;
            padding-right: 125px;
            margin-bottom: 167px;
            margin-top: 20px;
        }

        .bordeUpload {
            margin-bottom: 10px;
            margin-top: 20px;
            background-color: rgba(255,255,255,.3);
        }

        .bordeCuadros {
            border-radius: 10px;
        }

        .bordeCuadroGrande {
            border-radius: 10px;
            padding-bottom: 100px;
        }
    </style>

    <div class="columns">
        <div class="column ">

        </div>

        <div class="column fondoVerdeIzquierdo">
            <div class="logo columns">
                <div class="column is-one-quarter justificado2">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Fingerprint_picture.svg/200px-Fingerprint_picture.svg.png" height="300" width="300">
                </div>
                <div class="column justificado2 whiteHuella">
                    <p class="whiteHuella">Huellador <br /></p>
                    <p class="whiteFinger">Finger print recognition</p>
                    <p class="whiteFinger">Create your account</p>
                </div>
            </div>
            <label class="label  white">Full Name</label>
            <div class="centrado"><input class="input bordeCuadros" type="text" placeholder="Jhoe Done"></div>
            <label class="label  white">Email</label>
            <div class="control has-icons-left has-icons-right centrado">
                <input class="input is-left bordeCuadros" type="email" placeholder="e-mail" value="">
                <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                </span>
                <span class="icon is-small is-right"></span>
            </div>
            <label class="label  white">Phone Number</label>
            <div class="centrado"><input class="input bordeCuadros" type="text" placeholder="+52 5542718294"></div>
            <label class="label  white">Address</label>
            <div class="centrado"><input class="input bordeCuadroGrande" type="text" placeholder=""></div>
        </div>
        <div class="column fondoVerdeDerecho">
            <p class="whiteHuella ">Profile Picture <br /></p>
            <div class="justificadoUpload bordeUpload  ">
                <img src="https://png.icons8.com/windows/1600/upload-to-cloud.png" width="50" height="50" class="justificadoUploadI">
            </div>
            <label class="label justificado white">Organization</label>
            <div class="centrado"><input class="input bordeCuadros" type="text" placeholder="Example.org"></div>
            <label class="label justificado white">Password</label>
            <div class="centrado"><input class="input bordeCuadros" type="text" placeholder="**************"></div>

            <div class="justificado bordeDerecho white">
                <a class=" white" href="www.google.com">Submit</a>
            </div>
        </div>
        <div class="column">

        </div>
    </div>
</div>

huellador/Views/Shared/_Navbar.cshtml
<nav class="navbar">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            <img src="~/images/Logo_nav.PNG" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
        </a>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>

    <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-start">

        </div>
        <div class="navbar-end">
            <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                Home
            </a>
            <a class="navbar-item">
                Comparison
            </a>
            <a class="navbar-item">
                Verification
            </a>

            <a class="navbar-item" asp-area="" asp-controller="MyPeople" asp-action="PersonDisplay">
                People
            </a>

            <a class="navbar-item" asp-area="" asp-controller="Account" asp-action="Account">
                My Account
            </a>

        </div>


    </div>
</nav>


           